// apps/examples/nextjs-pages/components/footer.tsx
import CustomLink from "./custom-link"

export default function Footer() {
  return (
    <footer className="mx-0 my-4 flex w-full flex-col space-y-1 px-4 text-sm sm:px-6 md:mx-auto md:my-12 md:h-5 md:max-w-3xl md:flex-row md:items-center md:space-x-4 md:space-y-0">
      <CustomLink href="https://nxauth.khulnasoft.com">
        Documentation
      </CustomLink>
      <CustomLink href="https://www.npmjs.com/package/nxauth">NPM</CustomLink>
      <CustomLink href="https://github.com/khulnasoft/nxauth/tree/main/apps/examples/nextjs-pages">
        Source on GitHub
      </CustomLink>
      <CustomLink href="/policy">Policy</CustomLink>
    </footer>
  )
}

// apps/examples/sveltekit/src/components/footer.svelte
<script lang="ts">
  import packageJSON from "@nxauth/sveltekit/package.json"
  import ExternalIcon from "./external-icon.svelte"
</script>

<footer>
  <div>
    <a href="https://sveltekit.nxauth.khulnasoft.com"
      >Documentation <ExternalIcon /></a
    >
    <a href="https://www.npmjs.com/package/nxauth"> NPM <ExternalIcon /> </a>
    <a
      href="https://github.com/khulnasoft/nxauth/tree/main/apps/examples/sveltekit"
    >
      Source on GitHub <ExternalIcon />
    </a>
    <a class="no-underline" href="/policy">Policy</a>
  </div>
  <div>
    <img
      src="https://nxauth.khulnasoft.com/img/logo-sm.png"
      alt="Auth.js Logo"
    />
    <a href="https://www.npmjs.com/package/@nxauth/sveltekit">
      @nxauth/sveltekit@{packageJSON.version}
      <ExternalIcon />
    </a>
  </div>
</footer>

<style>
  footer {
    display: flex;
    width: 100%;
    justify-content: space-between;
    align-items: center;
    padding-inline: 1.25rem;
    margin-block: 2rem;
  }
  footer > div {
    gap: 1rem;
    display: flex;
    flex-wrap: wrap;
    align-items: center;
  }
  footer a {
    color: #333;
    text-underline-offset: 4px;
    font-weight: 500;
    display: flex;
    align-items: flex-end;
    gap: 0.25rem;
  }
  footer img {
    width: 24px;
    height: 24px;
  }
  .no-underline {
    text-decoration: none;
  }
</style>
