// apps/examples/nextjs/components/footer.tsx
import CustomLink from "./custom-link"
import packageJSON from "nxauth/package.json"

export default function Footer() {
  return (
    <footer className="mx-0 my-4 flex w-full flex-col gap-4 px-4 text-sm sm:mx-auto sm:my-12 sm:h-5 sm:max-w-3xl sm:flex-row sm:items-center sm:justify-between sm:px-6">
      <div className="flex flex-col gap-4 sm:flex-row">
        <CustomLink href="https://nxauth.khulnasoft.com">
          Documentation
        </CustomLink>
        <CustomLink href="https://www.npmjs.com/package/nxauth">NPM</CustomLink>
        <CustomLink href="https://github.com/khulnasoft/nxauth/tree/main/apps/examples/nextjs">
          Source on GitHub
        </CustomLink>
        <CustomLink href="/policy">Policy</CustomLink>
      </div>
      <div className="flex items-center justify-start gap-2">
        <img
          className="size-5"
          src="https://nxauth.khulnasoft.com/img/logo-sm.png"
          alt="Auth.js Logo"
        />
        <CustomLink href="https://npmjs.org/package/nxauth">
          {packageJSON.version}
        </CustomLink>
      </div>
    </footer>
  )
}

// apps/examples/sveltekit/src/components/footer.svelte
<script lang="ts">
  import packageJSON from "@nxauth/sveltekit/package.json"
  import ExternalIcon from "./external-icon.svelte"
</script>

<footer>
  <div>
    <a href="https://sveltekit.nxauth.khulnasoft.com"
      >Documentation <ExternalIcon /></a
    >
    <a href="https://www.npmjs.com/package/nxauth"> NPM <ExternalIcon /> </a>
    <a
      href="https://github.com/khulnasoft/nxauth/tree/main/apps/examples/sveltekit"
    >
      Source on GitHub <ExternalIcon />
    </a>
    <a class="no-underline" href="/policy">Policy</a>
  </div>
  <div>
    <img
      src="https://nxauth.khulnasoft.com/img/logo-sm.png"
      alt="Auth.js Logo"
    />
    <a href="https://www.npmjs.com/package/@nxauth/sveltekit">
      @nxauth/sveltekit@{packageJSON.version}
      <ExternalIcon />
    </a>
  </div>
</footer>

<style>
  footer {
    display: flex;
    width: 100%;
    justify-content: space-between;
    align-items: center;
    padding-inline: 1.25rem;
    margin-block: 2rem;
  }
  footer > div {
    gap: 1rem;
    display: flex;
    flex-wrap: wrap;
    align-items: center;
  }
  footer a {
    color: #333;
    text-underline-offset: 4px;
    font-weight: 500;
    display: flex;
    align-items: flex-end;
    gap: 0.25rem;
  }
  footer img {
    width: 24px;
    height: 24px;
  }
  .no-underline {
    text-decoration: none;
  }
</style>
